yolo_cfg_path: ./config/yolov3.cfg
yolo_weight_path: ./weight/yolov3.weights
yolo_net_resolution: 416
yolo_batch_size: 1
yolo_confidence: 0.9
yolo_nms_thresh: 0.4
yolo_num_classes: 80
yolo_classes_data: ./classes/coco.names
video_path: ./data/1.avi
tracking_object: traffic light
candidate_layer_range: [13,14,15,16,17,18,31,32,33,34,35,36,41,42,43,44,45,46,47,48,49,50]
tracker_activate_thresh: 5
tracker_padding: 1.5
tracker_lambdar: 0.001
tracker_interp_factor: 0.05
tracker_kernel_sigma: 0.5
tracker_output_sigma: 0.05
tracker_scale_gamma: 0.9
